Parameters:
  VendorName:
    Type: String
    Default: vna
    AllowedPattern: '^[a-z0-9]{2,32}$'
  S3BucketName:
    Type: String
    Default: archive
    AllowedPattern: '^[a-z0-9-]{4,40}$'
    ConstraintDescription: 3-63 characters; must contain only lowercase letters or numbers
  EnvironmentType:
    Type: String
    Default: pat 
    AllowedValues:
      - prd
      - tst
      - pat
      - dev
Resources:
  VendorS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketName: 
        Fn::Join:
          - '-'
          - - !Ref VendorName 
            - !Ref EnvironmentType
            - !Ref S3BucketName
      Tags:
        - Key: Vendor
          Value: !Ref VendorName 
        - Key: Environment
          Value: !Ref EnvironmentType
Outputs:
  BucketExport:
    Description: Bucket Resource Export for future cross-stack reference
    Value: !Ref 'VendorS3Bucket'
    Export:
      Name: !Join [":", [!Ref "AWS::StackName", VendorS3Bucket]]
